<h1>Welcome to My DVD List!</h1>

<p>Please login to view the DVD choices and information about each movie!</p>

<form action="?" method="POST">

<label for="username">Username:</label>
	<input type="text" name="username" id="username" maxlength="20" size="20" /><br/>
	
<label for="password">Password:</label>
	<input type="password" name="password" id="password" maxlength="20" size="20" /><br/>

<input type="submit" /><br/><br/>


</form>