<!DOCTYPE html>

<html lang="en">

	<head>	
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		
		<link rel="stylesheet" type="text/css" href="css/reset.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
		
		<!--Tab ICON-->
		<link rel="shortcut icon" href="images/logoURL.png" />
		
		<title>Home: Perfect For Me</title>
		
		<!-- GA, where should I add it?
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-47850929-1', 'perfectforme.org');
		  ga('send', 'pageview');

		</script>
		-->
		
		
	</head>

	<body>
		<header>
		<nav>
		
			<ul>
				<li><a href="index.html">Perfect for Me</a></li><!--logo link-->
				<li><a href="index.html">About</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>

			<form method="POST" action="?">
				<p>
				
				<!--<label for="email">Email: </label>-->
				<!--<input type="text" name="email" id="email" placeholder="Email" min="1" max="100" size="45"/>-->
				<label for="username">Username:</label>
				<input type="text" name="username" id="username" placeholder="should be Email" min="1" max="100" size="45" />
				
				</p>
				<p>
					<label for="password">Password: </label>
					<input type="password" name="password" id="password" placeholder="Password" min="1" max="100" size="45"/>
					
					<input type="submit" name="submit" value="Login" />
				</p>
				
			</form>
	
		</nav>
		</header>

