
<!-- The CTA photo, Why Join? and Create an Account Section on the Home page-->
		
<section id="cta">
	<p><img src="images/ctaImg.jpg" alt="Image of a woman's hands holding a small wrapped present" /></p>
</section>


<section id="registration">

	<div>
		<h1>Why Join?</h1>			
		<p> 
			Perfect For Me is a non-profit website that allows people to make a group 
			account to share each other’s gift profile to find and buy the perfect gift! 
		</p>
		<p>
			Includes - having your own gift profile where you can add gifts you want others to buy for you!
			A group calendar where everyone can add personal occasions for fellow group members to remember and celebrate!
			And the "Last Resort" which is a list of websites that do fast delivery if you need the perfect gift ASAP!
		</p>
		<p>
			Give it a try! Join today!
		</p>
				
	</div>

	<form>
		<fieldset>
			<legend>Create An Account</legend>				
			<p>
				<label for="firstName">First Name:</label>
				<input type="text" name="firstName" id="firstName" placeholder="" min="1" max="100" size="75">
			</p>
			<p>
				<label for="lastName">Last Name:</label>
				<input type="text" name="lastName" id="lastName" placeholder="" min="1" max="100" size="75">
			</p>
			<p>
				<label for="email">Email: </label>
				<input type="text" name="email" id="email" placeholder="" min="1" max="100" size="75">
			</p>
			<p>
				<label for="password">Password: </label>
				<input type="password" name="password" id="password" placeholder="" min="1" max="100" size="75">
			</p>	
			<p>	
				<input type="submit" name="submit" />
			</p>
		</fieldset>
	</form>

</section>		
